[tool.poetry]
name = "skill-map"
version = "0.1.0"
description = ""
authors = ["s-tsuchida-safie <s-tsuchida@safie.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
