[tool.poetry]
name = "skill-map"
version = "0.1.0"
description = ""
authors = ["s-tsuchida-safie <s-tsuchida@safie.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
databases = "^0.9.0"
pydantic-settings = "^2.7.1"
aiosqlite = "^0.20.0"
pytest-cov = "^6.0.0"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
flake8 = "^7.1.1"
pytest-asyncio = "^0.25.2"
pytest = "^8.3.4"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
